SELECT * FROM T_SIP_DEPTO ORDER BY 1 DESC;

CREATE SEQUENCE SQ_T_SIP_DEPTO
START WITH 1
INCREMENT BY 1
MAXVALUE 20
NOCYCLE;

INSERT INTO T_SIP_DEPTO(CD_DEPTO, NM_DEPTO, SG_DEPTO)
VALUES(SQ_T_SIP_DEPTO.NEXTVAL, 'Marketing digital', 'DMG');

SELECT SQ_T_SIP_DEPTO.CURRVAL FROM DUAL;

INSERT INTO T_SIP_DEPTO(CD_DEPTO, NM_DEPTO, SG_DEPTO)
VALUES(SQ_T_SIP_DEPTO.NEXTVAL, 'Automação industrial', 'DAI');


CREATE SEQUENCE SQ_T_SIP_FUNCIONARIO
START WITH 1
INCREMENT BY 1
NOCYCLE;

SELECT * FROM T_SIP_FUNCIONARIO;

INSERT INTO T_SIP_FUNCIONARIO
(NR_MATRICULA, CD_DEPTO, NM_FUNCIONARIO, DT_NASCIMENTO, DT_ADMISSAO, VL_SALARIO)
VALUES(SQ_T_SIP_FUNCIONARIO.NEXTVAL, 
SQ_T_SIP_DEPTO.CURRVAL, 
'Siath Sepol',
SYSDATE-13555,
SYSDATE,
DBMS_RANDOM.VALUE(13454, 31000)
);


ALTER SEQUENCE  SQ_T_SIP_DEPTO MAXVALUE 99;

--
--INSERT ALL
--

INSERT ALL
    INTO T_SIP_DEPTO(CD_DEPTO, NM_DEPTO, SG_DEPTO)
    VALUES(SQ_T_SIP_DEPTO.NEXTVAL, 'Lobby Relações Especiais', 'DMG')
    INTO T_SIP_FUNCIONARIO
    (NR_MATRICULA, CD_DEPTO, NM_FUNCIONARIO, DT_NASCIMENTO, DT_ADMISSAO, VL_SALARIO)
    VALUES(SQ_T_SIP_FUNCIONARIO.NEXTVAL, 
    SQ_T_SIP_DEPTO.CURRVAL, 
    'Ovatsug Silva',
    SYSDATE-18000,
    SYSDATE,
    DBMS_RANDOM.VALUE(13454, 31000)
    )
    INTO T_SIP_DEPENDENTE
    (NR_MATRICULA, CD_DEPENDENTE, NM_DEPENDENTE, DT_NASCIMENTO)
    VALUES(SQ_T_SIP_FUNCIONARIO.CURRVAL, 
    1, 
    'Leinad Silva',
    SYSDATE-5000)
    INTO T_SIP_DEPENDENTE
    (NR_MATRICULA, CD_DEPENDENTE, NM_DEPENDENTE, DT_NASCIMENTO)
    VALUES(SQ_T_SIP_FUNCIONARIO.CURRVAL, 
    2, 
    'Ana Silva',
    SYSDATE-3000)
SELECT * FROM DUAL;



--
--VERIFICANDO RESULTADO
--

SELECT * FROM T_SIP_DEPTO;
SELECT * FROM T_SIP_FUNCIONARIO;
SELECT * FROM T_SIP_DEPENDENTE;
COMMIT;

--
--IDENTICO AO MYSQL E SQL SERVER (AUTOINCREMENTO)
--

CREATE OR REPLACE TRIGGER TR_SIP_DEPTO_AUTO_INCREMENTO
BEFORE INSERT ON T_SIP_DEPTO
FOR EACH ROW
BEGIN
    :NEW.CD_DEPTO := SQ_T_SIP_DEPTO.NEXTVAL;
END;
/

--
--Sequence está na trigger que fica dentro da tabela emtão não precisamos mais espeificar a sequence
--


SELECT SQ_T_SIP_DEPTO.CURRVAL FROM DUAL;

INSERT INTO T_SIP_DEPTO(NM_DEPTO, SG_DEPTO)
VALUES('Top D+', 'TD+');

SELECT SQ_T_SIP_DEPTO.CURRVAL FROM DUAL;

SELECT * FROM T_SIP_DEPTO ORDER BY 1;
